name: Build and deploy to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_URL: europe-north2-docker.pkg.dev/jsfs-sthlm-2024-06-03/cloud-run-source-deploy/live-chat-frontend/live-chat-frontend:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - id: "auth"
        name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure docker
        run: gcloud auth configure-docker europe-north2-docker.pkg.dev

      - name: Docker Build
        run: docker build --build-arg VITE_CLERK_PUBLISHABLE_KEY="${{ vars.VITE_CLERK_PUBLISHABLE_KEY }}" VITE_SOCKET_URL="${{ vars.VITE_SOCKET_URL }}" VITE_API_URL="${{ vars.VITE_API_URL }}"--no-cache -t ${{ env.IMAGE_URL }} . -f Dockerfile

      - name: Docker Push
        run: docker push $IMAGE_URL

      - name: Update Cloud Run service
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          region: europe-north2
          service: live-chat-frontend
          image: ${{ env.IMAGE_URL }}
